# @package _group_

fairseq:
  task:
    _name: unpaired_audio_text
    labels: phn
    data: ???
    sort_by_length: false
    shuffle: false
    text_data: ''

  common_eval:
    path: ???
    quiet: false

  dataset:
    max_tokens: 11000000
    gen_subset: valid
    batch_size: 1
    required_batch_size_multiple: 1 ## it is very important

w2l_decoder: KALDI
kaldi_decoder_config:
    hlg_graph_path: /workspace2/maduo/dataset/format/librispeech/librispeech_lm_norm_phn_seq/fst/phn_to_words_sil/HLG.phn.kenlm.wrd.o40003.fst
    #output_dict: /workspace2/maduo/dataset/format/librispeech/librispeech_lm_norm_phn_seq/lexicon_filtered.lst ## word2phoneseq 
    #output_dict:  /workspace2/maduo/dataset/format/librispeech/librispeech_lm_norm_phn_seq/fst/phn_to_words_sil/kaldi_dict.h_out.phn.txt ## phone2id
    output_dict:  /workspace2/maduo/dataset/format/librispeech/librispeech_lm_norm_phn_seq/fst/phn_to_words_sil/kaldi_dict.kenlm.wrd.o40003.txt  ## word2id dictionary
    #kaldi_initializer_config:
    #  data_dir: /workspace2/maduo/dataset/format/librispeech/librispeech_lm_norm_phn_seq/phonesss
    #  fst_dir: /workspace2/maduo/dataset/format/librispeech/librispeech_lm_norm_phn_seq/fst/phn_to_words_sil
    #  in_labels: phn
    #  wav2letter_lexicon: /workspace2/maduo/dataset/format/librispeech/librispeech_lm_norm_phn_seq/lexicon_filtered.lst
    #  lm_arpa: /workspace2/maduo/dataset/format/librispeech/librispeech_lm_norm_phn_seq/kenlm.wrd.o40003.arpa
    #  kaldi_root: /workspace2/maduo/pykaldi/tools/kaldi
    #  blank_symbol: "<SIL>"

    acoustic_scale: 0.5
    max_active: 10000
    beam_delta: 0.5
    hash_ratio: 2.0

    is_lattice: True
    lattice_beam: 10.0
    prune_interval: 25
    determinize_lattice: True
    prune_scale: 0.1
    ## when max_mem: 120, the running logger is as follows:
    #LOG ([5.5.950~1-085be]:RebuildRepository():determinize-lattice-pruned.cc:287) Rebuilding repository.
    ##WARNING ([5.5.950~1-085be]:CheckMemoryUsage():determinize-lattice-pruned.cc:320) Did not reach requested beam in determinize-lattice: size exceeds maximum 120 bytes; (repo,arcs,elems) = (25760,480,5784), after rebuilding, repo size was 12448, effective beam was 7.72374 vs. requested beam 10
    ##[2023-05-29 20:57:44,304][root][WARNING] - Lattice determinization is terminated early because at least one of max_mem, max_loop or max_arcs thresholds was reached. If you want a more detailed log message, rerun this function after setting verbose level > 0 using kaldi.base.set_verbose_level.
    max_mem: 20000000  # its unit is bytes max_mem: 120, its means that in determinize-lattice: size exceeds maximum 120 bytes. it should be big number e.g. 20000000, you can reference kaldi recipe setting (kaldi/egs/wsj/s5/steps/nnet3/get_degs.sh) 
    phone_determinize:  True
    word_determinize:  True
    minimize: True

    num_threads: 20    
post_process: silence
results_path: ???
decode_stride: 1
#targets: none  ## if it is none, will not computer wer, if it is wrd, will commputer wer
#lm_model: none  ## it is kenlm  or fairseqlm path
#lexicon: none
beam_threshold: 100.0
beam: 1500
word_score: 1.0 ## default  1.0
sil_weight: 0.0 ## default 0.0
lm_weight: 2.0  ## default 2.0

hydra:
  run:
    dir: ${results_path}/viterbi  ## logger store directory.
  sweep:
    dir: ${results_path}
    subdir: viterbi

