# @package _group_

fairseq:
  task:
    _name: unpaired_audio_text
    labels: phn
    data: ???
    sort_by_length: false
    shuffle: false
    text_data: ''

  common_eval:
    path: ???
    quiet: true

  dataset:
    max_tokens: 11000000
    gen_subset: valid
    batch_size: 1
    required_batch_size_multiple: 1 ## it is very important

w2l_decoder: VITERBI_FRAME
post_process: silence
results_path: ???
decode_stride: 1

hydra:
  run:
    dir: ${results_path}/viterbi_frame  ## logger store directory.
  sweep:
    dir: ${results_path}
    subdir: viterbi_frame

